services:
  db:
    image: postgres
    container_name: search-flow
    restart: always
    environment:
      POSTGRES_USER: search-flow_user
      POSTGRES_PASSWORD: search-flow_password
      POSTGRES_DB: search-flow-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: trawl-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console UI
    volumes:
      - minio_data:/data

  scylla-node1:
    image: scylladb/scylla:5.4
    container_name: scylla-node1
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 384M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode=1
    ports:
      - "9042:9042"
      - "10000:10000"
    volumes:
      - scylla_data1:/var/lib/scylla
    networks:
      - scylla-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 30

  scylla-node2:
    image: scylladb/scylla:5.4
    container_name: scylla-node2
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 384M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode=1
    ports:
      - "9043:9042"
    volumes:
      - scylla_data2:/var/lib/scylla
    depends_on:
      scylla-node1:
        condition: service_healthy
    networks:
      - scylla-net
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 30

  scylla-node3:
    image: scylladb/scylla:5.4
    container_name: scylla-node3
    restart: always
    command: --seeds=scylla-node1 --smp 1 --memory 384M --overprovisioned 1 --api-address 0.0.0.0 --developer-mode=1
    ports:
      - "9044:9042"
    volumes:
      - scylla_data3:/var/lib/scylla
    depends_on:
      scylla-node1:
        condition: service_healthy
      scylla-node2:
        condition: service_healthy
    networks:
      - scylla-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: trawl-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq_user
      RABBITMQ_DEFAULT_PASS: rabbitmq_password
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data:
  scylla_data1:
  scylla_data2:
  scylla_data3:

networks:
  scylla-net:
    driver: bridge
